### ISSUE TITLE
JRE prerequisite are not mentionned in README

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepqwat2ili#107]
Looks like we miss some prerequisite definition.

```
Info: dbschema <pg2ili_abwasser>
Info: dburl <jdbc:postgresql://postgis2.pully.ch:5432/qgep_demo>
Info: dbusr <postgres>
Error: org.postgresql.util.PSQLException: SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)
Error:   SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)
```

**Comment by sjib** [comment]
See here https://github.com/QGEP/qgepqwat2ili/issues/57

**Comment by sjib** [comment]
Detailed description how to change from `scram-sha-256` to `md5`: https://github.com/opengisch/QgisModelBaker/issues/779#issuecomment-1406333971

**Comment by sjib** [comment]
@ponceta Prerequisits are specified in the docs: https://github.com/QGEP/docs/blob/master/en/admin-guide/interlis-io/index.rst#prerequisites

Please make a suggestion on how to adapt https://github.com/QGEP/qgepqwat2ili#readme

**Comment by sjib** [comment]
Solved with https://github.com/QGEP/qgepqwat2ili/pull/134

@ponceta Please reopen if needed
