### ISSUE TITLE
INTERLIS-Export: dataowner and provider are not implemented

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/qgepqwat2ili#113]
**Describe the bug**
Datenherr and Datenlieferant are exported always as unknown, also when there are values in this fields.

This is not a bug (it's documentated in the code), but the correct values are not implemented.

**Comment by sjib** [comment]
See https://github.com/QGEP/qgepqwat2ili/issues/36 for more background and considerations

**Comment by sjib** [comment]
Needs adaption here:
`            datenherr=getattr(row.fk_dataowner__REL, "name", "unknown"),  # TODO : is unknown ok ?`
 `           datenlieferant=getattr(row.fk_provider__REL, "name", "unknown"),  # TODO : is unknown ok ?`

See https://github.com/QGEP/qgepqwat2ili/blob/df62333539ec7197becb1ad0f604a35f29c8b98b/qgepqwat2ili/qgep/export.py#L96

Suggested Change Options:
a) Change "name" to "identifier" as there is no column "name" in qgep datamodel in class organisation to get the identifier in case there is no fk_ set
b) It should only set 'unknown' if there is no fk_provider set.  Just add 'unknown' if there is no fk_ set (becaus if NULL then we get an error in the INTERLIS file) and else leave the foreignkey value

**Comment by sjib** [comment]
With obj_id instead of name:
`            datenherr=getattr(row.fk_dataowner__REL, "obj_id", "unknown"),  # TODO : is unknown ok ?`
 `           datenlieferant=getattr(row.fk_provider__REL, "obj_id", "unknown"),  # TODO : is unknown ok ?`

![20230331_datenherr_datenlieferant_obj_id_instead_name](https://user-images.githubusercontent.com/1265865/229195484-ddd259ee-b114-4936-b90b-77493d7d9ce1.jpg)

**Comment by sjib** [comment]
Please vote with thumb which of the two option should be implemented.

**Comment by sjib** [comment]
Should be correct now with obj:

https://github.com/QGEP/qgepqwat2ili/blob/2455a6a71da44ea58e2a98b421dc35db9e657830/qgepqwat2ili/qgep/export.py#L123

https://github.com/QGEP/qgepqwat2ili/blob/2455a6a71da44ea58e2a98b421dc35db9e657830/qgepqwat2ili/qgepdss/export.py#L128

https://github.com/QGEP/qgepqwat2ili/blob/2455a6a71da44ea58e2a98b421dc35db9e657830/qgepqwat2ili/qgepsia405/export.py#L121

@urskaufmann Please check and confirm, then this can be closed.

**Comment by sjib** [comment]
@urskaufmann I close this issue - please re-open if still an issues with the current plugin version.
