### ISSUE TITLE
SIA405 Import: Missing Info-Window

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/qgepqwat2ili#119]
**Describe the bug**
The info-window disappears after 33% (Import XTF-data). I get no more info about progress or about log-files. 

**To Reproduce**
Exact steps to reproduce the behavior:
Import a SIA405 -xtf

**Expected behavior**
Information about the steps that are realised (with time-stamps) and about the steps that are remaining

**Screenshots / data**
-

**Desktop (please complete the following information):**
- QGEP plugin version 20230411 test vsa-dss
- QGEP datamodel version 1.6.0
- QGEP project file version 1.6.0
- QGIS Version 3.28.5
- OS Win 10

**Additional context**
Importing the same data that made the error described in #118 , but SIA405 instead of DSS.
Import is slow!

**Comment by sjib** [comment]
Is improved in import for TEKSI Wastewater - could be backported to qgep also
![interlis_import_windows](https://github.com/QGEP/qgepqwat2ili/assets/1265865/7b6fd02b-d6cd-4919-8b49-e641c981c151)

**Comment by sjib** [comment]
![20240511_qgep_nachrichtenprotokoll_gekuerzt](https://github.com/QGEP/qgepqwat2ili/assets/1265865/2f6dbc71-67ba-4776-a5ff-f82b1e1d5445)

**Comment by sjib** [comment]
Solved with https://github.com/QGEP/qgepqwat2ili/pull/141
