### ISSUE TITLE
Allow to configure pg_service from commandline

### ISSUE THREAD

**Issue by olivierdalang** [QGEP/qgepqwat2ili#12]
currently hardcoded, we need to be able to define that

**Comment by olivierdalang** [comment]
done

**Comment by sjib** [comment]
So the new example in the readme should be:

python -m qgepqwat2ili qwat export **--pgservice qwat_demo** desktop/my_export.xtf

[qwat_demo]
#enter your database ip
host=localhost
#database name
dbname=qwat
port=5432
user=postgres
#you can also add your password if you like
password=***
