### ISSUE TITLE
Error upon import IV

### ISSUE THREAD

**Issue by meierrom** [QGEP/qgepqwat2ili#125]
Hi folks,

I'm getting the following error message upon issuing an import command:

python -m qgepqwat2ili qgep import data/heit/heitsia405export_20230505.xtf --log

[...]
psycopg2.errors.ForeignKeyViolation: insert or update on table "wastewater_networkelement" violates foreign key constraint "rel_wastewater_networkelement_wastewater_structure"
DETAIL:  Key (fk_wastewater_structure)=(bauwer0000400074) is not present in table "wastewater_structure".
[...]
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "wastewater_networkelement" violates foreign key constraint "rel_wastewater_networkelement_wastewater_structure"
DETAIL:  Key (fk_wastewater_structure)=(bauwer0000400074) is not present in table "wastewater_structure".
[SQL: INSERT INTO qgep_od.wastewater_networkelement (obj_id, identifier, remark, last_modification, fk_dataowner, fk_provider, fk_wastewater_structure) VALUES (%(obj_id)s, %(identifier)s, %(remark)s, %(last_modification)s, %(fk_dataowner)s, %(fk_provider)s, %(fk_wastewater_structure)s)]
[parameters: (

{'obj_id': 'netzel0000403284', 'identifier': 'ak2783', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000400074'}, 
{'obj_id': 'netzel0000402944', 'identifier': 'ak463', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000399734'}, 
{'obj_id': 'netzel0000403526', 'identifier': 'ak2229', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000400316'}, 
{'obj_id': 'netzel0000403422', 'identifier': 'ak2279', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000400212'}, 
{'obj_id': 'netzel0000403423', 'identifier': 'ak2168', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000400213'}, 
{'obj_id': 'netzel0000403424', 'identifier': 'ak2175', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000400214'}, 
{'obj_id': 'netzel0000403049', 'identifier': 'ak262', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000399839'}, 
{'obj_id': 'netzel0000403425', 'identifier': 'ak2173', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000400215'} 

... displaying 10 of 4285 total bound parameter sets ...  
{'obj_id': 'netzel0000409713', 'identifier': 'ha2529', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000407032'}, 
{'obj_id': 'netzel0000409727', 'identifier': 'ha2543', 'remark': None, 'last_modification': datetime.date(2023, 4, 27), 'fk_dataowner': None, 'fk_provider': None, 'fk_wastewater_structure': 'bauwer0000407046'}
)]
[...]

Any ideas what's going wrong?

Kind regards,
Roman

**Comment by sjib** [comment]
There was another issue with the same type of violation: https://github.com/QGEP/qgepqwat2ili/issues/118

**Comment by meierrom** [comment]
Hi @sjib,

> There was another issue with the same type of violation: #118
Yeah, thanks! It's not really helping me though.

Anyway, I had a closer look at my issue and I was somehow able to reproduce things with a single sql statement, e.g. 

INSERT INTO qgep_od.wastewater_networkelement (obj_id, identifier, remark, last_modification, fk_dataowner, fk_provider, fk_wastewater_structure)
VALUES ('netzel0000403284','ak2783','00000000OG000000', '2023-04-27', '00000000OG000000', '00000000OG000000', 'bauwer0000400074')
;

ERROR:  insert or update on table "wastewater_networkelement" violates foreign key constraint "rel_wastewater_networkelement_wastewater_structure"
DETAIL:  Key (fk_wastewater_structure)=(bauwer0000400074) is not present in table "wastewater_structure".

Fact is that in my case no data was ever imported into table gep_od.wastewater_structure. This should have been done in an earlier step, right? Therefore it doesn't come as a surprise that qgepqwat2ili is complaining about a missing key related to table gep_od.wastewater_structure.

The question here may be, why qgepqwat2ili failed to import any data into table wastewater_structure and then moving on to table gep_od.wastewater_networkelement without throwing any error message.

Kind regards,
Roman

**Comment by meierrom** [comment]
Hi folks,

I was trying to narrow down my issue by reducing the xtf file to just two records, one "Normschacht" and one "Abwasserknoten".

Surprisingly the import is failing as well issuing the same error message as above.

What's wrong with my data?

This is the file content I used:

<?xml version="1.0" encoding="UTF-8"?><TRANSFER xmlns="http://www.interlis.ch/INTERLIS2.3">
<HEADERSECTION SENDER="ili2pg-4.5.0-fc023c8d2d8cd44d792927e45dc80c1ad973f095" VERSION="2.3"><MODELS><MODEL NAME="SIA405_ABWASSER_2015_LV95" VERSION="17.04.2018" URI="http://www.sia.ch/405"></MODEL></MODELS></HEADERSECTION>
<DATASECTION>
<SIA405_ABWASSER_2015_LV95.SIA405_Abwasser BID="SIA405_ABWASSER_2015_LV95.SIA405_Abwasser">
<SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht TID="ch13p7mzMA002320"><OBJ_ID>ch13p7mzMA002320</OBJ_ID><Metaattribute><SIA405_Base_LV95.Metaattribute><Datenherr>unknown</Datenherr><Datenlieferant>unknown</Datenlieferant><Letzte_Aenderung>20210810</Letzte_Aenderung></SIA405_Base_LV95.Metaattribute></Metaattribute><Baujahr>1800</Baujahr><Bezeichnung>SE5</Bezeichnung><Sanierungsbedarf>unbekannt</Sanierungsbedarf><Status>in_Betrieb</Status><Funktion>Kontrollschacht</Funktion></SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht>
<SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten TID="ch13p7mzWN006889"><OBJ_ID>ch13p7mzWN006889</OBJ_ID><Metaattribute><SIA405_Base_LV95.Metaattribute><Datenherr>unknown</Datenherr><Datenlieferant>unknown</Datenlieferant><Letzte_Aenderung>20180404</Letzte_Aenderung></SIA405_Base_LV95.Metaattribute></Metaattribute><Bezeichnung>SE5</Bezeichnung><AbwasserbauwerkRef REF="ch13p7mzMA002320"></AbwasserbauwerkRef><Lage><COORD><C1>2750585.641</C1><C2>1263701.746</C2></COORD></Lage><Sohlenkote>392.650</Sohlenkote></SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten>
</SIA405_ABWASSER_2015_LV95.SIA405_Abwasser>
</DATASECTION>
</TRANSFER>

Kind regards,
Roman

**Comment by sjib** [comment]
follow up see also https://github.com/QGEP/qgepqwat2ili/issues

**Comment by sjib** [comment]
See also https://github.com/QGEP/QGEP/issues/852

**Comment by sjib** [comment]
Should be solved with https://github.com/QGEP/datamodel/pull/235
