### ISSUE TITLE
qgepqwat2ili: exported labels' TID are no standardoid

### ISSUE THREAD

**Issue by cymed** [QGEP/qgepqwat2ili#132]
**Describe the bug**
When exporting a Model including labels, the labels have a purely numerical TID .

**To Reproduce**
Exact steps to reproduce the behavior:
1. Export an xtf with labels through the GUI
2. Check a feature's TID in class 'xx_Text' 
3. TID is numeric

**Expected behavior**
TID is a valid standardoid as required by SIA405_Base. My take on this would be: 

1. Separate the label export from the interlis export
    1.1. Add a DB- side view tww_od.vw_text for import and export
    1.2. Add a UI to import labels into tww_od.txt_text and the corresponding specialised table (i.e. tww_od.reach_text)
    1.3 Potential problem: We are currently limited to 1 million OID per class, see https://github.com/QGEP/QGEP/discussions/764. When we truncate and re-import the labels every time we want to make an export, this might be reached quite fast
2. Altering the export scripts to use the label positions in the database instead of the ones in the QGIS project. Importing the labels into 

**Screenshots / data**
![grafik](https://github.com/QGEP/qgepqwat2ili/assets/102035587/1d47f6d6-9684-457a-a73b-692f4b132471)

**Desktop (please complete the following information):**
 - QGEP plugin version: 1.6.1
 - QGEP datamodel version: 1.6.0 with necessary PR for VSA DSS 2015 Export (https://github.com/QGEP/qgepqwat2ili/tree/2023-03_interlis_additional_models_new)
 - QGEP project file version: 1.6.0
 - QGIS Version: 3.28.11
 - OS: Windows

**Additional context**

**Comment by sjib** [comment]
@cymed 

- Label export was not intended to do a data exchange but export only for geoportals that cannot place labels in a optimized position.
- Do you get validation errors in INTERLIS with numeric TID?
- If yes, with which datamodel(s)?

**Comment by cymed** [comment]
I get no validation errors from ilivalidator, but the canton of Aargau requires all tids to be standardoids according to an extended validation check (relevant for AG64/96 gateway that is in the planning)

**Comment by sjib** [comment]
But label_position are a "waste" product that will change with a next data delivery and cannot be maintained - so this makes no sense to me to set a stable OID there.

**Comment by cymed** [comment]
I agree conceptually, but as long as some cantonal offices require stable oid, the engineering companies must deliver them.

**Comment by sjib** [comment]
@cymed Do we still have to solve this in qgep? Else please close and add issue to tww

**Comment by cymed** [comment]
Is solved already in tww. Closing here
