### ISSUE TITLE
qwat Export - wrong format Letzte_Aenderung

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#16]
When I test qwat export I get a couple of ERROR messages:

Info: ilivalidator-1.11.10-61c230a3331fd24f2c1dc841ee9519e191915440
Info: ili2c-5.2.2-c48675a2ecb4cf824bcbdcaa76abfdb10bea327e
Info: iox-ili-1.21.6-4c681c10b36fc582a611709d0ee9bf426177876f
Info: User <Stefan>
Info: Start date 2021-06-24 11:11
Info: maxMemory 4147200 KB
Info: dataFile <C:\Daten\qwat\qwatexport.xtf>
Info: modelNames <SIA405_WASSER_2015_LV95>
Info: modeldir <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels;C:\temp\2020\Organisation\ilimodels;C:\temp\2020\sia405abwasser;C:\Daten\Dropbox\in_Arbeit\VSACHECK_2015\Transferdatensatz2015>
Info: lookup model <SIA405_WASSER_2015_LV95> 2.3 in repository <C:\Daten\qwat/>
Info: lookup model <SIA405_Base> 2.3 in repository <C:\Daten\qwat/>
Info: lookup model <Units> 2.3 in repository <C:\Daten\qwat/>
Info: lookup model <Base> 2.3 in repository <C:\Daten\qwat/>
Info: ilifile <C:\Daten\qwat\Units.ili>
Info: ilifile <C:\Daten\qwat\Base_d-20181005.ili>
Info: ilifile <C:\Daten\qwat\SIA405_Base_d-20181005.ili>
Info: ilifile <C:\Daten\qwat\SIA405_Wasser_2015_2_d-20181005.ili>
Info: validate data...
Info: assume unknown external objects
Info: first validation pass...
Error: line 16: SIA405_WASSER_2015_LV95.SIA405_Wasser.Hydraulischer_Knoten: tid 8293: value <8293> is not a valid OID
**Error: line 16: SIA405_WASSER_2015_LV95.SIA405_Wasser.Hydraulischer_Knoten: tid 8293: value <00011230> is not in range in attribute Metaattribute[0]/Letzte_Aenderung**

For Letzte_Aenderung create a valid **INTERLIS_1_Date** here that looks like yyyymmdd:
https://github.com/QGEP/qgepqwat2ili/blob/4de7f7b576baf717f62a05ad6d4bbed6e96673fe/qgepqwat2ili/qwat/export.py#L79

	`STRUCTURE Metaattribute =
	!! Metainformationen - bitte auch auf www.geocat.ch erfassen
      Datenherr: MANDATORY OrganisationBezeichnung;  !! Datenherr, also diejenige Person oder Stelle, die berechtigt ist, diesen Datensatz zu löschen, zu ändern, zu verwalten. Falls ein Ingenieurbüro dies im Auftrag einer Gemeinde wahrnimmt, so ist die Gemeinde als Datenherr einzusetzen und nicht das Ingenieurbüro. Dieses wird dann unter Datenlieferant aufgeführt.
      Datenlieferant: MANDATORY OrganisationBezeichnung;  !! Organisation, die diesen Datensatz erzeugt hat (siehe auch Datenherr und Letzte_Aenderung)
      Letzte_Aenderung: MANDATORY INTERLIS.INTERLIS_1_DATE;  !! ! Datum der letzten Änderung dieses Datensatzes, falls diese Information vorhanden ist. Falls nicht vorhanden Datum der Erzeugung des Transferdatensatzes einsetzen.
	END Metaattribute;`

**Comment by olivierdalang** [comment]
should be fixed in master

**Comment by sjib** [comment]
Please set to current date instead of dummy value: The data model specifies:

`Date of the last modification of this record, if this information is available. If not available, insert date of creation of the transfer record.`

Letzte_Aenderung: MANDATORY INTERLIS.INTERLIS_1_DATE;  !! ! Datum der letzten Änderung dieses Datensatzes, falls diese Information vorhanden ist. Falls nicht vorhanden Datum der Erzeugung des Transferdatensatzes einsetzen.
