### ISSUE TITLE
qwat Export - OID not valid

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#17]
When I test qwat export I get a couple of ERROR messages:

Info: ilivalidator-1.11.10-61c230a3331fd24f2c1dc841ee9519e191915440
Info: ili2c-5.2.2-c48675a2ecb4cf824bcbdcaa76abfdb10bea327e
Info: iox-ili-1.21.6-4c681c10b36fc582a611709d0ee9bf426177876f
Info: User <Stefan>
Info: Start date 2021-06-24 11:11
Info: maxMemory 4147200 KB
Info: dataFile <C:\Daten\qwat\qwatexport.xtf>
Info: modelNames <SIA405_WASSER_2015_LV95>
Info: modeldir <%ITF_DIR;http://models.interlis.ch/;%JAR_DIR/ilimodels;C:\temp\2020\Organisation\ilimodels;C:\temp\2020\sia405abwasser;C:\Daten\Dropbox\in_Arbeit\VSACHECK_2015\Transferdatensatz2015>
Info: lookup model <SIA405_WASSER_2015_LV95> 2.3 in repository <C:\Daten\qwat/>
Info: lookup model <SIA405_Base> 2.3 in repository <C:\Daten\qwat/>
Info: lookup model <Units> 2.3 in repository <C:\Daten\qwat/>
Info: lookup model <Base> 2.3 in repository <C:\Daten\qwat/>
Info: ilifile <C:\Daten\qwat\Units.ili>
Info: ilifile <C:\Daten\qwat\Base_d-20181005.ili>
Info: ilifile <C:\Daten\qwat\SIA405_Base_d-20181005.ili>
Info: ilifile <C:\Daten\qwat\SIA405_Wasser_2015_2_d-20181005.ili>
Info: validate data...
Info: assume unknown external objects
Info: first validation pass...
Error: line 16: SIA405_WASSER_2015_LV95.SIA405_Wasser.Hydraulischer_Knoten: tid 8293: **value <8293> is not a valid OID**

For the OID it looks like qwat has not the same ID system as QGEP - so we would need to discuss tomorrow whether we generate valid OID in the export script or whether qwat will change to the same ID system with INTERLIS STANDARDOID as QGEP. 

For a quick solution you could generate valid OID with having a prefix (either as parameter in the script or read it from somewhere in qwat_sys) and generate the postfix part filling up the integer ID with leading zeros up to eight charaters: e.g. prefix ch123456 plus postfix 00000829 -> ch12345600000829

**Comment by olivierdalang** [comment]
should be fixed in master
