### ISSUE TITLE
Log message flood the CI

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepqwat2ili#172]
**Describe the bug**

`Mapping of wastewater_structure->abwasserbauwerk is not fully implemented.`
`QGEP field special_structure.upper_elevation has no equivalent in the interlis model. It will be ignored.`
`[repeated 11298 times]`
```
Could not find value `None` in value list "qgep_vl.manhole_material". Setting to None instead.
Could not find value `None` in value list "qgep_vl.manhole_material". Setting to None instead.
.................................................[repeated 48 times]
[repeated 48 times]
```

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
This message only gives hints that 3D is not fully implemented. Could also be set to debug mode.

**Comment by sjib** [comment]
Solved with https://github.com/QGEP/qgepqwat2ili/pull/171
