### ISSUE TITLE
qwat Export - Attribute Metaattributes has wrong number of values

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#18]
There are some more basic errors: In class Leitung the class **SIA405_Base_LV95.Metaattribute is written twice**: e.g. Error: line 213479: SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung: tid 26973: Attribute Metaattribute has wrong number of values
![qwat_install_qgepqwat2ili_003_metaattributes_wrong_number_values](https://user-images.githubusercontent.com/1265865/123396373-86072c00-d5a1-11eb-84f0-85bcc26bba58.jpg)

**Comment by sjib** [comment]
We also have objects with no Metaattributes:

		<SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung TID="21531">
				<OBJ_ID>21531</OBJ_ID>
				<Metaattribute>
					<SIA405_Base_LV95.Metaattribute>
						<Datenherr>unknown</Datenherr>
						<Datenlieferant>unknown</Datenlieferant>
						<Letzte_Aenderung>00011230</Letzte_Aenderung>
					</SIA405_Base_LV95.Metaattribute>
					<SIA405_Base_LV95.Metaattribute>
						<Datenherr>unknown</Datenherr>
						<Datenlieferant>unknown</Datenlieferant>
						<Letzte_Aenderung>00011230</Letzte_Aenderung>
					</SIA405_Base_LV95.Metaattribute>
				</Metaattribute>
			</SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung>
			<SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung TID="19577">
				<OBJ_ID>19577</OBJ_ID>
			</SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung>
			<SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung TID="1628">
				<OBJ_ID>1628</OBJ_ID>
			</SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung>
			<SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung TID="1906">
				<OBJ_ID>1906</OBJ_ID>
			</SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung>
			<SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung TID="26148">
				<OBJ_ID>26148</OBJ_ID>
				<Metaattribute>
					<SIA405_Base_LV95.Metaattribute>
						<Datenherr>unknown</Datenherr>
						<Datenlieferant>unknown</Datenlieferant>
						<Letzte_Aenderung>00011230</Letzte_Aenderung>
					</SIA405_Base_LV95.Metaattribute>
				</Metaattribute>
			</SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung>

**Comment by olivierdalang** [comment]
This should be fixed
