### ISSUE TITLE
qwat Export - duplicate OID Leitung / Hydraulischer Knotenn

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#19]
A next on is, that you cannot use the same tid twice: 

Error: line 223786: SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung: tid 14523: **OID** 14523 of object SIA405_WASSER_2015_LV95.SIA405_Wasser.Leitung **already exists in CLASS** SIA405_WASSER_2015_LV95.SIA405_Wasser.Hydraulischer_Knoten.

**Comment by sjib** [comment]
As we have discussed we skip the Hydraulic classes (Hydraulischer_Knoten / Hydraulischer_Strang) for now as they do not exist in qwat currently and it is also unclear how they are correctly used in the SIA405_Wasser model. Then this problem does not arise anymore. 

If it would be implementated later again, we would need to discuss how to generate a valid and stable OID for those classes.

**Comment by olivierdalang** [comment]
should be fixed in master (not yet disabled hydraulic classes, but fixed generated OID uniqueness)
