### ISSUE TITLE
Adapt KEK datamodel to version 2019

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#20]
Adapt VSA-KEK datamodel from version 2008 (currently implemented in qgep) to the new version 2019
https://www.vsa.ch/models/2019/VSA_KEK_2019_2_d_LV95-20210416.ili

**Comment by sjib** [comment]
See https://github.com/QGEP/datamodel/pull/177

**Comment by olivierdalang** [comment]
merged
