### ISSUE TITLE
Prepare for user testing

### ISSUE THREAD

**Issue by olivierdalang** [QGEP/qgepqwat2ili#21]
Steps to get a testable pre-release

 
QGEPPLUGIN
- [x] merge https://github.com/QGEP/qgepplugin/pull/65 (plugin release workflow update that should allow to deal with prereleases)
- [x] merge https://github.com/QGEP/qgepplugin/pull/66 (allow to use a pre-release from the data-init tool)
- [x] merge https://github.com/QGEP/qgepplugin/pull/58 (qgepqwat2ili integration in the plugin)
- [x] update previous QGEPPLUGIN releases to be not experimental
- [x] make a pre-release of the plugin (probably tag 1.6.0-beta) - should be flagged as experimental ?

QGEP DATAMODEL
- [x] finish & merge https://github.com/QGEP/datamodel/pull/177
- [x] no need for tagged release yet (testers will test from master)

QGEP QGIS PROJECT
- [x] no need for tagged release yet (testers will test from master)

QWAT DATAMODEL
- [x] requires fix of https://github.com/qwat/QWAT/issues/313

QGEPQWAT2ILI
- [x] have qwat export validate on the demodata (e.g. this must pass, or at least yield actual validation issues https://github.com/QGEP/qgepqwat2ili/pull/22) - for now this passes only with --skip_hydraulics
- [x] have qwat export validate on the demodata without --skip_hydraulics (optional, we could already test without hydraulics)
- [x] check other issues in [milestone user testing](https://github.com/QGEP/qgepqwat2ili/milestone/1)

**Comment by sjib** [comment]
@olivierdalang I named my datamodel update 1.5.6 -> should I rename it? See https://github.com/QGEP/datamodel/pull/177

**Comment by sjib** [comment]
@oliver-ch Can you update above what has been done in the meantime?

**Comment by olivierdalang** [comment]
Done (you've pinged the wrong oliver by the way :-) )
