### ISSUE TITLE
SIA405_Water missing Spezialbauwerk

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#27]
I do not see yet how the class Spezialbauwerk is matched from qwat. For all objects Anlage, Wasserbehaelter, Wassergewinnungsanlage, Foerderanlage and weitere in addition to the Leitungsknoten a Spezialbauwerk should be created with the geometry (Geometrie, Art and Metaattributes) as MANDATORY attributes.

https://github.com/QGEP/qgepqwat2ili/blob/8bd11d5ddc9bd455247440e141ccbcad842a6446/qgepqwat2ili/qwat/mapping.py#L35

**Comment by olivierdalang** [comment]
Ok done.

It seems there's no row with polygon_geometry in the demo data set, so validity of this output will not be tested automatically (I just tested with one very simple polygon). If this feature is commonly used, it would be good to adapt the QWAT demo dataset to cover this use case.
