### ISSUE TITLE
Error: illegal value null for Bemerkung

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#33]
Next testing with 1.5.6-b5:
Export stops with warning: illegal value null for Bemerkung

In the logs:
r0.T_Id=? (TransferToXtf.java:682)
Info: readObjectTid(): SELECT T_Id,T_Ili_Tid,T_Type FROM (SELECT r1.T_Id, r1.T_Ili_Tid, r1.T_Type FROM pg2ili_abwasser.baseclass r1) r0 WHERE r0.T_Id=? (TransferToXtf.java:682)
Error: **illegal value null for Bemerkung**
Error:     ch.interlis.iom_j.Iom_jObject.setattrvalue(Iom_jObject.java:389)
Error:     ch.ehi.iox.objpool.impl.AbstractIomObjectSerializer.readIomObject(AbstractIomObjectSerializer.java:297)
Error:     ch.ehi.ili2db.toxtf.FixIomObjectRefsSerializer.getObject(FixIomObjectRefsSerializer.java:17)
Error:     ch.ehi.ili2db.toxtf.FixIomObjectRefsSerializer.getObject(FixIomObjectRefsSerializer.java:11)
Error:     ch.ehi.iox.objpool.impl.BTreeImpl.readValue(BTreeImpl.java:132)
Error:     ch.ehi.iox.objpool.impl.BTreeImpl.access$200(BTreeImpl.java:21)
Error:     ch.ehi.iox.objpool.impl.BTreeImpl$3.next(BTreeImpl.java:233)
Error:     ch.ehi.ili2db.toxtf.TransferToXtf.doBasket(TransferToXtf.java:613)
Error:     ch.ehi.ili2db.toxtf.TransferToXtf.doit(TransferToXtf.java:296)
Error:     ch.ehi.ili2db.base.Ili2db.transferToXtf(Ili2db.java:2372)
Error:     ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1781)
Error:     ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:219)
Error:     ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:559)
Error:     ch.ehi.ili2pg.PgMain.main(PgMain.java:70)

![20210825_interlisexport_arbon3_error](https://user-images.githubusercontent.com/1265865/130794311-de976508-7799-439d-b33b-02068ba3e940.jpg)

[ili2qgepqwat-2021-08-25-13-41-10-export.log.zip](https://github.com/QGEP/qgepqwat2ili/files/7047089/ili2qgepqwat-2021-08-25-13-41-10-export.log.zip)

**Comment by sjib** [comment]
Not clear to me how a field "Bemerkung" can become NULL in QGEP.

**Comment by sjib** [comment]
![20210825_wastewater_structure_remark_null](https://user-images.githubusercontent.com/1265865/130795338-d489804b-c611-4008-8ccc-81114f523029.jpg)

**Comment by sjib** [comment]
In INTERLIS remark (Bemerkung) is not MANDATORY. Did we mix remark and identifier (Bemerkung and Bezeichnung) somewhere in the code?

**Comment by sjib** [comment]
I checked the data in den POSTGIS schema checking how far it went with the xtf Export and saw that it was on exporting Haltungspunkt. Checking there I saw these lines with Bemerkung that are empty (instead of NULL):
![20210830_bemerkung_is_not_null](https://user-images.githubusercontent.com/1265865/131668300-5ff7bd4f-983f-4f7e-ba5f-07f99ecd2419.jpg)

**Comment by sjib** [comment]
How can this be fixed without overwriting the existing 'Bemerkung' in the table haltungspunkt respective reach_point if correcting in the gep_od schema?

This statement will overwrite existing remarks, as they are also NOT NULL:
```
UPDATE qgep_od.reach_point
SET remark = NULL
where remark IS NOT NULL;
```

This gets all the data with an exisiting remark and NOT NULL
`SELECT * FROM qgep_od.reach_point where (remark IS NOT NULL OR remark <> '');`

How do I only get the data with remark that is empty (lines 1-6 above in the screenshot) and set them to NULL?

**Comment by sjib** [comment]
@olivierdalang So the problem is that we have an empty 'remark' in the qgep_od schema instead of [Null] and that is causing the export problem. 
Any idea why this can happen? 

This is not very logic for the user to change himself / herself in QGEP and the export tool should be able to fix that automatically.

**Comment by olivierdalang** [comment]
I'll add a hack to transform empty strings to NULL, but the proper place to fix that is in ili2db, as empty strings do not exactly mean the same thing as NULL.

Also if we don't use the nuance between empty strings and NULL in QGEP, we could open an issue on QGEP to either make these fields non-nullable with default to empty string, or add a check constraint to forbid empty strings.

About your question above, it should work with this, no ?
```sql
UPDATE qgep_od.reach_point
SET remark = NULL
WHERE remark = '';
```

**Comment by sjib** [comment]
> I'll add a hack to transform empty strings to NULL, but the proper place to fix that is in ili2db, as empty strings do not exactly mean the same thing as NULL.

@olivierdalang Ok, please do so - you know best the difference and can raise the issue and document the case as we have it.

**Comment by sjib** [comment]
> Also if we don't use the nuance between empty strings and NULL in QGEP, we could open an issue on QGEP to either make these fields non-nullable with default to empty string, or add a check constraint to forbid empty strings.

Good idea - I started a new discussion for this: https://github.com/QGEP/QGEP/discussions/687

**Comment by olivierdalang** [comment]
I tried to reproduce this, but here it works even with empty strings.

Can you provide exact steps on how to reproduce this on the test dataset (incl. if needed SQL to change the values of bemerkung to get failing rows) ?

**Comment by olivierdalang** [comment]
I'm not able to reproduce here... I tried both from the command line and from the GUI.

I've opened a PR that should fix this : https://github.com/QGEP/qgepqwat2ili/pull/52

Ideally, rather than merging it, we should find out why you're getting this issue while I don't, as it could hide some other bug. Are you able to reproduce the issue on the demo dataset ? If so, can you provide exact steps (including SQL commands to alter the demo dataset) ?

**Comment by sjib** [comment]
@olivierdalang I used the demo project - may be an older version.

>  The empty field contains: '' when I open to edit it.

So did you also have **''** in an empty field in your project as described above? (screenshots) or was it "really" empty, meaning no **''** when you edit and display?

**Comment by olivierdalang** [comment]
I tried with both NULLs and empty strings
