### ISSUE TITLE
How to set dataowner / provider if Null in Database

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#36]
https://github.com/QGEP/qgepqwat2ili/blob/50b8b8758d4ecaaf06e1b7dccdb156a9813a098b/qgepqwat2ili/qgep/export.py#L67

@olivierdalang Do I understand right, that it is set to "unknown" if is Null in QGEP at the moment
![wastewater_structure_fk_dataowner_provider_null](https://user-images.githubusercontent.com/1265865/130801612-7dcbff2c-9f57-4d23-b748-75ba0a1d8302.jpg)
?

**Comment by olivierdalang** [comment]
Yes that should be the current behavior.

Can users not just fix that in their data if actually the owner is actually known ?

**Comment by sjib** [comment]
Yes, that would be the correct way to correct the data. 

In the INTERLIS models the value "unknown" has a special meaning and is not the same as an empty (or Null) value. "unknown" means that someone has invested time and money to find out about a certain attribute, but did not find another value. Therefore writing "unknow" would imply that you did not find out who is the dataowner / provider. So my question is whether we should not better leave it empty as we do now also with the other attributes, so it would be clearer, that this data is missing.

In the next release (2020) of SIA405 Abwasser / VSA-DSS these two attributes will also be referenced to organisation (as e.g. owner) in the INTERLIS model and will therefore also be treated as reference keys. The user then has to fill them out anyway to have a valid export.
