### ISSUE TITLE
Allow selection of postgres config service in user interface

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#39]
Currently qgepqwat2ili  does not yet support the --pgservice option by providing a pulldown selection in the user interface of INTERLIS import / export. 

The option is available already in the command line tool version:

python -m qgepqwat2ili qwat [-h] [--recreate_schema] [--skip_validation] [**--pgservice PGSERVICE**] [--log] [--include_hydraulics] {import,export} path

Maybe the code from the datamodel tool could be reused to make a selection in a similar way:
![datamodel_tool_pgconf_selection](https://user-images.githubusercontent.com/1265865/130921218-332736c1-5cfe-466d-a714-d2bfec1a9988.jpg)

**Comment by olivierdalang** [comment]
As said in #42 : Supporting other connection types is of course possible, but there are potentially many cases to support (.pgpassword, qgis encrypted configs, maybe more ?), hence more work and more maintenance burden. Note that we must be able to retrieve the full connection info, incl. unencrypted password, as we need to provide those to ili2pg.

**Comment by sjib** [comment]
I think in a first enhancement would be just to be able to choose from the defined pg_services also in the QGEP plugin as this is currently hardwired to pg_service = qwat resp. pg_service = pg_qgep. 

Other connection options would need to be solved more globally for qwat / qgep and not to point of this issue.

**Comment by olivierdalang** [comment]
Ok, I've made a change so that instead of hardcoding to pg_qgep it takes the service from the currently loaded layer.

As said above, this is less error prone (you export or import to what's currently open).
