### ISSUE TITLE
testdata_vsa_kek_2019_manhole_damage_8486_identifierref.xtf Import does not create link to wastewater_structure

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#4]
When I import testdata_vsa_kek_2019_manhole_damage_8486_identifierref.xtf I get the warning, that wastewater_structure 8486 is not found. 
![testdata_vsa_kek_2019_manhole_damage_8486_identifierref_009_21052021_104531](https://user-images.githubusercontent.com/1265865/119143300-bf4ef800-ba47-11eb-955a-304592a8f0ff.jpg)

But why does the wizard not look up the wastewater_structure.identifier and suggests a match?

 <vonPunktBezeichnung>8486</vonPunktBezeichnung> is provided!

![testdata_vsa_kek_2019_manhole_damage_8486_identifierref_021_21052021_144534](https://user-images.githubusercontent.com/1265865/119143412-daba0300-ba47-11eb-8797-f5f3641380f4.jpg)

The import interface should support both relation systems: by identifier and by oid ref

**Comment by sjib** [comment]
Should work the same way as with channel_damage: https://github.com/QGEP/qgepqwat2ili/issues/9

**Comment by olivierdalang** [comment]
Ok done.

Can you confirm that the following logic is correct :

- an examination with both `vonPunktBezeichnung` and `bisPunktBezeichnung` should be assign to corresponding Channel
- an examination with only `vonPunktBezeichnung` should be assign to corresponding Manhole
- no assignation in other cases (only `bisPunktBezeichnung` or neither)

As far as I understand, nothing prevents from having an examination linked to a manhole that then has channel damages

**Comment by sjib** [comment]
It's decided by the damage subclasses what is needed: 
A manhole damage must have have a `vonPunktBezeichnung` and/or `HaltungspunktRef` (either referenced by Bezeichnungen or referenced by OID of objects - in this case Haltungspunkt
A channel damage must have have a  `vonPunktBezeichnung` and `bisPunktBezeichnung` and/or `HaltungspunktRef` and `AbwasserbauwerkRef` (either referenced by Bezeichnungen or referenced by OID of objects - in this case Haltungspunkt and Abwasserbauwerk. If both are provided the OID references should be prioritized).

**Comment by sjib** [comment]
> As far as I understand, nothing prevents from having an examination linked to a manhole that then has channel damages

Yes, the datamodel does not check that. This is true.
