### ISSUE TITLE
Export is invalid - not a valid OID

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepqwat2ili#43]
WARNING    Invalid file : The created file is not a valid XTF file.

Info: ilivalidator-1.11.9-7dab04f1037b40b6219ae2e584b3fcc1bc10726d
Info: ili2c-5.1.5-35f2a1fe63ea46830bc886ae50a3a818125c8eb9
Info: iox-ili-1.21.4-3757f7907f90ae2bef2be7c97d50d11770fc5f1f
Info: User <pulpoar>
Info: Start date 2021-09-01 13:57
Info: maxMemory 253440 KB
Info: dataFile <U:/Downloads/qgep-export.xtf>
Info: pluginFolder <C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\bin\ilivalidator-1.11.9\plugins>
Info: modeldir <C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili>
Info: lookup model <Units> 2.3 in repository <C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili/>
Info: lookup model <Base> 2.3 in repository <C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili/>
Info: lookup model <SIA405_Base> 2.3 in repository <C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili/>
Info: lookup model <SIA405_ABWASSER_2015> 2.3 in repository <C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili/>
Info: lookup model <VSA_KEK_2019_LV95> 2.3 in repository <C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili/>
Info: ilifile <C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili\Units.ili>
Info: ilifile <C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili\Base_d-20181005.ili>
Info: ilifile <C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili\SIA405_Base_d-20181005.ili>
Info: ilifile <C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili\SIA405_Abwasser_2015_2_d-20180417.ili>
Info: ilifile <C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\ili\VSA_KEK_2019_2_d_LV95-20210120.ili>
Info: validate data...
Info: assume unknown external objects
Info: first validation pass...
Error: line 5: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Kanal: tid 00000000CL000000: value <00000000CL000000> is not a valid OID
Error: line 6: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Kanal: tid 00000000CL000001: value <00000000CL000001> is not a valid OID
Error: line 7: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Kanal: tid 00000000CL000002: value <00000000CL000002> is not a valid OID
Error: line 8: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht: tid 00000000WS000003: value <00000000WS000003> is not a valid OID
Error: line 9: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht: tid 00000000WS000004: value <00000000WS000004> is not a valid OID
Error: line 10: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht: tid 00000000WS000005: value <00000000WS000005> is not a valid OID
Error: line 11: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht: tid 00000000WS000002: value <00000000WS000002> is not a valid OID
Error: line 12: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt: tid 00000000RP000000: value <00000000RP000000> is not a valid OID
Error: line 13: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt: tid 00000000RP000001: value <00000000RP000001> is not a valid OID
Error: line 14: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt: tid 00000000RP000002: value <00000000RP000002> is not a valid OID
Error: line 15: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt: tid 00000000RP000003: value <00000000RP000003> is not a valid OID
Error: line 16: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt: tid 00000000RP000004: value <00000000RP000004> is not a valid OID
Error: line 17: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt: tid 00000000RP000005: value <00000000RP000005> is not a valid OID
Error: line 18: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten: tid 00000000WN000003: value <00000000WN000003> is not a valid OID
Error: line 19: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten: tid 00000000WN000004: value <00000000WN000004> is not a valid OID
Error: line 20: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten: tid 00000000WN000005: value <00000000WN000005> is not a valid OID
Error: line 21: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten: tid 00000000WN000002: value <00000000WN000002> is not a valid OID
Error: line 22: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung: tid 00000000RE000000: value <00000000RE000000> is not a valid OID
Error: line 23: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung: tid 00000000RE000001: value <00000000RE000001> is not a valid OID
Error: line 24: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung: tid 00000000RE000002: value <00000000RE000002> is not a valid OID
Error: line 25: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Deckel: tid 00000000CO000003: value <00000000CO000003> is not a valid OID
Error: line 26: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Deckel: tid 00000000CO000004: value <00000000CO000004> is not a valid OID
Error: line 27: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Deckel: tid 00000000CO000005: value <00000000CO000005> is not a valid OID
Error: line 28: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Deckel: tid 00000000CO000002: value <00000000CO000002> is not a valid OID
Info: second validation pass...
Info: validate unique constraint SIA405_Base_LV95.SIA405_BaseClass.Constraint1...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_BetreiberAssoc.BetreiberRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_EigentuemerAssoc.EigentuemerRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_TextAssoc.Text...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_BetreiberAssoc.BetreiberRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_EigentuemerAssoc.EigentuemerRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.BauwerksTeil_AbwasserbauwerkAssoc.BauwerksTeil_AbwasserbauwerkAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserbauwerk_SymbolAssoc.Symbol...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwassernetzelement_AbwasserbauwerkAssoc.Abwassernetzelement_AbwasserbauwerkAssocRef...
Info: validate multiplicity of role VSA_KEK_2019_LV95.KEK.Erhaltungsereignis_AbwasserbauwerkAssoc.Erhaltungsereignis_AbwasserbauwerkAssocRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.BauwerksTeil_AbwasserbauwerkAssoc.AbwasserbauwerkRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.BauwerksTeil_AbwasserbauwerkAssoc.AbwasserbauwerkRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwassernetzelement_AbwasserbauwerkAssoc.AbwasserbauwerkRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_RohrprofilAssoc.RohrprofilRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_nachHaltungspunktAssoc.nachHaltungspunktRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_vonHaltungspunktAssoc.vonHaltungspunktRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwassernetzelement_AbwasserbauwerkAssoc.AbwasserbauwerkRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt_AbwassernetzelementAssoc.Haltungspunkt_AbwassernetzelementAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_nachHaltungspunktAssoc.nachHaltungspunktRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_AlternativVerlaufAssoc.Alternativverlauf...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_TextAssoc.Text...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_vonHaltungspunktAssoc.vonHaltungspunktRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_RohrprofilAssoc.RohrprofilRef...
Info: validate target of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt_AbwassernetzelementAssoc.AbwassernetzelementRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_nachHaltungspunktAssoc.Haltung_nachHaltungspunktAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung_vonHaltungspunktAssoc.Haltung_vonHaltungspunktAssocRef...
Info: validate multiplicity of role SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt_AbwassernetzelementAssoc.AbwassernetzelementRef...
Info: validate multiplicity of role VSA_KEK_2019_LV95.KEK.Untersuchung_HaltungspunktAssoc.Untersuchung_HaltungspunktAssocRef...
Info: U:/Downloads/qgep-export.xtf: VSA_KEK_2019_LV95.KEK BID=VSA_KEK_2019_LV95.KEK
Info:       4 objects in CLASS SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Abwasserknoten
Info:       4 objects in CLASS SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Deckel
Info:       3 objects in CLASS SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltung
Info:       6 objects in CLASS SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Haltungspunkt
Info:       3 objects in CLASS SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Kanal
Info:       4 objects in CLASS SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Normschacht
Info: ...validation failed

**Comment by ponceta** [comment]
Selection export successfull but invalid

[qgep-export.zip](https://github.com/QGEP/qgepqwat2ili/files/7090863/qgep-export.zip)

**Comment by sjib** [comment]
OK, this looks good at least from the user experience and installation

The only problem is that you have [not set a proper prefix in qggep_sys](https://qgep.github.io/docs/installation-guide/workstation.html#add-your-own-oid-in-the-project) and the prefix '00000000' is used that creates none valid OID:

`Error: line 5: SIA405_ABWASSER_2015_LV95.SIA405_Abwasser.Kanal: tid 00000000CL000000: value <**00000000**CL000000> is not a valid OID`

@ponceta Do you have a dataset with all valid OID you can export? Or delete the few channels and manholes that were created with none valid prefix and try again?

**Comment by ponceta** [comment]
We should provide somewhere in QGEP plugin a way to set the prefix. This was already a user request.

I'll provide same export with a valid oid prefix.

**Comment by sjib** [comment]
We had some thoughts on this here: https://github.com/QGEP/QGEP/issues/548

**Comment by olivierdalang** [comment]
I'll close this in the meantime as this feature is not directly linked to ili export.

@ponceta please reopen if export doesn't work despite valid oids
