### ISSUE TITLE
Selection on wastewater structure exports only nodes

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#46]
When selecting structures only structures will be exported - channels and reaches will be missing.

![gep_export_selection_wastewater_structures](https://user-images.githubusercontent.com/1265865/131705668-a3b1691d-fae8-42ad-b005-6223662f8f94.jpg)

[20210901_qgep-export_selection_wastewater_structures.zip](https://github.com/QGEP/qgepqwat2ili/files/7092742/20210901_qgep-export_selection_wastewater_structures.zip)

When you want to export the whole network, then you have to make a selection on the vw_gep_reach layer.

**Comment by sjib** [comment]
@olivierdalang Is that what you intended to implement?

**Comment by sjib** [comment]
@ponceta @urskaufmann @varrieta @kandre @TriformMoritz @tproduit @PeterZamudio Is that good from a user perspective?

**Comment by urskaufmann** [comment]
if I want to export all related classes, I make a selection on reaches (not on nodes). The problem in this case are nodes (wastewater structures), that are not connected to any reach. So: if there is a selection on the reaches, I should be able to select additional wastewater structures, and this structure selection should expand the reach selection.

**Comment by olivierdalang** [comment]
In theory the behavior is just like what Urs described.

If you encounter cases where it doesn't work as expected (which is quite possible as it's not been thoroughly tested yet) can you please specify exactly which nodes/reaches are selected, which ones you expected to be exported, and which one actually got exported ? (all that on the dataset)

This way I can reproduce the issue, and even add an automated test to ensure it keeps working.

**Comment by olivierdalang** [comment]
Closing this, please reopen if there's actually an issue.

**Comment by sjib** [comment]
> So: if there is a selection on the reaches, I should be able to select additional wastewater structures, and this structure selection should expand the reach selection.

@urskaufmann I can select both layers first and then I get reaches and wastewater_structures selected (see screenshot):

![gep_export_selection_how_to_select_reach_and_wastewater_structure_select_bothlayers](https://user-images.githubusercontent.com/1265865/131841319-b5bbb545-87b2-4d00-9771-3214efb15628.jpg)

I will also post the result when the export is finished.

**Comment by ponceta** [comment]
A QGIS multi layer select tool would be great in this context :

https://github.com/qgis/QGIS/issues/45218
