### ISSUE TITLE
Bemerkung too long

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#50]
![qwat schadenstelle_bemerkung_too_long_80](https://user-images.githubusercontent.com/1265865/132573701-716aa9fe-ba92-49fd-861b-15b6acccd965.jpg)

Export fails because Bemerkung is maxium TEXT*80

**Comment by sjib** [comment]
Seems to be quite common in data of SIGE
![qwat schadenstelle_bemerkung_too_long_80_count](https://user-images.githubusercontent.com/1265865/132574986-a76386f7-c146-40c8-b02a-818869ed35c3.jpg)

@ponceta @kandre : Do we want to just crop on the export to the first 80 characters? Or not match description to Bemerkung at all?

**Comment by ponceta** [comment]
I will face same challenge with qgep SIA 405 export, for production purposes we use an unlimited Text field format for remarks.

If the SIA fields will remain so restrictive, we will have to crop the export or not match the remark fields at all.

If we define remark fields as intern needs only, I would be in favor of not matching it.

If we consider remark fields as important side information for the people who will use the exported data, I would be in favor of changing its length in the SIA norm itself.

_Side question is unlimited text format supported in interlis?_

**Comment by olivierdalang** [comment]
Fixed in https://github.com/QGEP/qgepqwat2ili/pull/54 (by truncating)

> Side question is unlimited text format supported in interlis?

It was just added to 4.6.0 (see https://github.com/claeis/ili2db/issues/402) with the `--sqlColsAsText`. I haven't tested though, and not sure if everything else works as expected.

If exporting invalid but non-truncated data is preferred, we could switch to that behavior instead in a future release. If so, please open a new feature ticket.

**Comment by sjib** [comment]
Good for now.
I would suggest as general principal that our export interface tries to export as is whereever possible and that things you have to change in qgep/qwat show up in the ilivalidator protocoll. Else we would have to change the interface when the datamodel we want to export into changes. I know that this does not work for everything and maybe needs some more experience day by day.

**Comment by olivierdalang** [comment]
Yes agreed, I'm trying to follow that approach unfortunately the ili2db step adds many hard constraints prevent from doing so. We'll see at some point if the `--sqlColsAsText` helps (but would rather not do that for version 1.0 as it will probably require more changes)
