### ISSUE TITLE
INTERLIS Import / Export - Java error - missing JDK libraries

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#57]
I tried to install the QGEP plugin on a new computer and got the following error when using INTERLIS import / export function:

```
2021-11-26T16:23:22        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Info: dburl 
             Info: dbusr 
             SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions) 
             Info: ili2pg-4.5.0-fc023c8d2d8cd44d792927e45dc80c1ad973f095 
             Info: ili2c-5.2.0-8af364826071f5feaae6f3d07a42518af082e083 
             Info: iox-ili-1.21.5-3b5a7efa5c363f77a4da188affead4d51dc38438 
             Info: java.version 1.8.0_311 
             Info: user.name 
             Info: maxMemory 3679232 KB 
             Info: currentTime 2021-11-26 16:23:22 
             Info: dbschema 
             Info: dburl 
             Info: dbusr 
             org.postgresql.util.PSQLException: SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions) 
              SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions) 
```
             
@olivierdalang Is there a command to install this library - something like: `pip install **`

Does this dependancy also needs to be check with the data model tool of QGEP? If yes please create an extra issue.

**Comment by olivierdalang** [comment]
@sjib This is a java error, so unfortunately not pip-installable...

ili2db docs specify these requirements : `JRE (Java Runtime Environment) installed on your system, version 1.6`. Can you check which version of java you've installed ? (output of `java -version`)

The data model tool should not be affected by that as it does not rely on java at all.

**Comment by sjib** [comment]
Now also documented in ili2db: see https://github.com/claeis/ili2db/issues/448
