### ISSUE TITLE
Import QGEP: error and missing docu 

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/qgepqwat2ili#59]
Tried to import a SIA405.xtf, got a error:  
_Invalid file : The input file is not a valid XTF file. Open the logs for more details on the error._
The details in the log-File did not help:
_Info: ilivalidator-1.11.9-7dab04f1037b40b6219ae2e584b3fcc1bc10726d
Info: ili2c-5.1.5-35f2a1fe63ea46830bc886ae50a3a818125c8eb9
Info: iox-ili-1.21.4-3757f7907f90ae2bef2be7c97d50d11770fc5f1f
Info: User <KAU>
Info: Start date 2022-04-13 13:47
Info: maxMemory 6291456 KB
Info: dataFile <P:/Thun/Gemeinden/246>
Info: dataFile <Krattigen/O1379>
Info: dataFile <GEP>
Info: dataFile <Krattigen/3>
Info: dataFile <TP>
Info: dataFile <ZSU/2021>
Info: dataFile <KTV>
Info: dataFile <ITS>
Info: dataFile <Perimeter>
Info: dataFile <B/042346-GEP_Krattigen_Perimeter_B.xtf>
Info: pluginFolder <C:\Users\KAU\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\bin\ilivalidator-1.11.9\plugins>
Error: java.io.FileNotFoundException: P:\Thun\Gemeinden\246 (The system cannot find the file specified)
Error:   P:\Thun\Gemeinden\246 (The system cannot find the file specified)_

Can it be, that the problem are blanks in the path of my xtf-file? This is a normal Windows-path, should work!!

The QGEP Docu (chapt. 3.3) does not really help (if I look at the picture in 3.3.3.3, I guess it's just a KEK-Import, no SIA405-part)
There should by described: Which xtf-File can be imported, which Version? SIA405 and/or KEK
What happens with data, that is already in the database, when I do the import?

**Comment by urskaufmann** [comment]
see also QGEP Issue 726: also problem with space/blank in path!

**Comment by beistehen** [comment]
This looks indeed like a path issue. From your log file:

> Info: dataFile <P:/Thun/Gemeinden/246>
> Info: dataFile <Krattigen/O1379>
> Info: dataFile
> Info: dataFile <Krattigen/3>
> Info: dataFile
> Info: dataFile <ZSU/2021>
> Info: dataFile
> Info: dataFile
> Info: dataFile
> Info: dataFile <B/042346-GEP_Krattigen_Perimeter_B.xtf>

Your path containing blanks is interpreted as if you wanted to process 10 different .xft files (one per line).

_Workaround 1_
Put double quotes ("...") around the complete path (including file name).

_Workaround 2_
Put your .xtf in a location where the path does not contain any special characters (like blanks and so on), e. g. `C:\Temp\`

**Comment by sjib** [comment]
Created pull request for updated documentation: https://github.com/QGEP/docs/pull/181

**Comment by sjib** [comment]
> see also https://github.com/QGEP/QGEP/issues/726: also problem with space/blank in path!

Supporting file pathes with space / blank see there
