### ISSUE TITLE
Easier access to import log files

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#6]
It would be nice to have easier access to the created log file(s) and not have to lock the path up in the protocoll window:
![testdata_vsa_kek_2019_manhole_damage_8486_oidref_034_21052021_162828](https://user-images.githubusercontent.com/1265865/119153524-9f243680-ba51-11eb-84fb-600efda8f767.jpg)

Maybe a window could show up that would allow to check the logs.
[ili2qgepqwat-2021-05-21-16-20-46-import.log](https://github.com/QGEP/qgepqwat2ili/files/6523199/ili2qgepqwat-2021-05-21-16-20-46-import.log)

I guess it would be the same also for exports.

**Comment by olivierdalang** [comment]
Ok added a button to open the logs using the standard editor :

![image](https://user-images.githubusercontent.com/1894106/119692414-ab423680-be4b-11eb-8bff-9f5efa606347.png)
