### ISSUE TITLE
Bemerkung not always truncated to 80 characters

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#63]
In INTERLIS  
`Bemerkung: TEXT*80;  !! Bemerkungen`  is always limited to 80 characters.

So these classes below should also be truncated as e.g. wastewater_structure:
https://github.com/QGEP/qgepqwat2ili/blob/ee505602be5c7153717c88fad3700a33036bb673/qgepqwat2ili/qgep/export.py#L120

Missing truncate:

Organisation:
https://github.com/QGEP/qgepqwat2ili/blob/ee505602be5c7153717c88fad3700a33036bb673/qgepqwat2ili/qgep/export.py#L183
Rohrprofil:
https://github.com/QGEP/qgepqwat2ili/blob/ee505602be5c7153717c88fad3700a33036bb673/qgepqwat2ili/qgep/export.py#L405
Haltungspunkt:
https://github.com/QGEP/qgepqwat2ili/blob/ee505602be5c7153717c88fad3700a33036bb673/qgepqwat2ili/qgep/export.py#L447
Untersuchung:
https://github.com/QGEP/qgepqwat2ili/blob/ee505602be5c7153717c88fad3700a33036bb673/qgepqwat2ili/qgep/export.py#L794
Datentraeger:
https://github.com/QGEP/qgepqwat2ili/blob/ee505602be5c7153717c88fad3700a33036bb673/qgepqwat2ili/qgep/export.py#L945

At @urskaufmann @TriformMoritz: 

- [ ] Any hesitations to change this? 
- [ ] Or do we want to keep an error message on the export if these remarks are too long in QGEP? 
- [ ] Or do we want to limit Bemerkung to 80 characters in the QGEP datamodel also? (as remarks are not intended to store data)

@ponceta has commented on this already: https://github.com/QGEP/qgepqwat2ili/issues/50#issuecomment-915796662

**Comment by TriformMoritz** [comment]
Personally, I put a lot of information to the remarks when I do not have a corresponding attribute or want to keep track of changes.
So I would be happy to have at least 200 characters (if not more or even unlimited) inside QGEP and also in Interlis.

**Comment by sjib** [comment]
For history please use the [historization plugin](https://qgep.github.io/docs/user-guide/history/history.html )
Remarks should not be missused to collect data - please propose new technical attributes if you are missing them. Migrating data that has been stored in the remark field is a very costly task.

**Comment by sjib** [comment]
In https://github.com/QGEP/qgepqwat2ili/issues/50#issuecomment-920195512 we decided to truncate - but https://github.com/QGEP/qgepqwat2ili/pull/54/files did not adapt this to all classes.
So I made a pull request with the missing classes to adapt:

**Comment by sjib** [comment]
And added a note for the documentation: https://github.com/QGEP/docs/pull/209

.. note:: Note that remark fields are truncated to 80 characters on INTERLIS Export, as the INTERLIS definition is like this. If you have remark fields with more text then consider to move this data to documentation with the classes "file" and "data_media" so it can be exported to INTERLIS completely where you can add any document, photo or video to a class.
