### ISSUE TITLE
Reserved key word class in python

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#72]
**class** is a reserved key word in python, so we are running into conflict with python when trying to write matchings such as:

 ```
File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgepdss\export.py", line 309
              klasse=row.class,
              ^
             SyntaxError: invalid syntax
```

Therefore it is suggested to rename all attributes "class" to "classname" in the qgep datamodel:

- qgep_od.mutation.class
- qgep_od.txt_text.class
- qgep_od.txt_symbol.class

[delta_1.5.7_dss_upddate_attributes_class.zip](https://github.com/QGEP/qgepqwat2ili/files/9103662/delta_1.5.7_dss_upddate_attributes_class.zip)

**Comment by sjib** [comment]
Need so that [https://github.com/teksi/Home/issues/15](https://github.com/teksi/Home/issues/15) can be implemented

**Comment by ponceta** [comment]
This is merged on datamodel side, you can test on master datamodel and this will be production ready when the release 1.6.0 is published.
