### ISSUE TITLE
Missing parameters ili2pg when password not set in pg_conf

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#76]
When I want to import an INTERLIS file and have not set the password in the pg_conf of that database then qgepqwat2ili raises an error during schema creation that the `--pwd` parameter has no value.

**Comment by sjib** [comment]
1. Is this a behaviour that is ok like this and just the documentation should be updated?
2. Or should the process be adjusted so that the interface asks for the missing password?
3. Would we have to look at it a bit more general and discuss about the whole process of configuration with pg_config? Are there other methods used? Which ones?

Thanks for your feedbacks on this.

**Comment by urskaufmann** [comment]
Just document is a bad solution
Ask for missing password is a/the solution
Don't no anything about other methods

**Comment by olivierdalang** [comment]
Fix incoming here: https://github.com/QGEP/qgepqwat2ili/pull/97

**Comment by ponceta** [comment]
Can we close this since #97 is merged?

**Comment by sjib** [comment]
@ponceta Not clear for me - for Urs it seems to work, my tests did not work - see https://github.com/QGEP/qgepqwat2ili/pull/97#issuecomment-1453820741

Maybe you could check also.

**Comment by ponceta** [comment]
Maybe run the check with some other INTERLIS user?

I'll try it but I see that we have some key aspects which have to be tackle down like what QGIS auth methods are supported on TEKSI modules (according to the actual doc it is pg_services using pg_conf), but many users do use many different auth methods.

I created a new feature request here :
https://github.com/QGEP/QGEP/issues/804

**Comment by ponceta** [comment]
Let's close this and reopen if any other user need is provided.

**Comment by urskaufmann** [comment]
Does not work with QGEP Plugin 1.6.0-rc.4, if there is no password in the pg_service.conf:
KAU is not the database, KAU is the username!

Ein Fehler trat bei der Ausführung von Python-Code auf: 

psycopg2.OperationalError: connection to server at "xxxx" (nnn.nnn.nn.nn), port 5432 failed: FATAL:  database "KAU" does not exist 
Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 197, in action_do_export
    create_ili_schema(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 13, in create_ili_schema
    connection = psycopg2.connect(get_pgconf_as_psycopg2_dsn())
  File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "xxxx" (nnn.nnn.nn.nn), port 5432 failed: FATAL:  database "KAU" does not exist



Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.2-Firenze Firenze, b47e00ba601 

Python-Pfad:
C:/PROGRA~1/QGIS3/apps/qgis/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis/./python/plugins
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA~1\QGIS3\apps\Python39\DLLs
C:\PROGRA~1\QGIS3\apps\Python39\lib
C:\Program Files\QGIS3\bin
C:\Users\KAU\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS3\apps\Python39
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python
P:/Thun/Gemeinden/246 Krattigen/O1379 GEP Krattigen/qgep
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.
