### ISSUE TITLE
Import Channel damage - Why is examination fk11abk6w70loo08 not selected?

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#8]
Importing testdata_vsa_kek_2019_channel_damage_8486_identifierref.xtf

![testdata_vsa_kek_2019_channel_damage_8486_identifierref_043_21052021_165733](https://user-images.githubusercontent.com/1265865/119157761-cbda4d00-ba55-11eb-9a90-14926ae91ddf.jpg)

Why is examination fk11abk6w70loo08 not selected?

**Comment by olivierdalang** [comment]
Damages of type `BCD` are unchecked by default, matching behavior in wincan2qgep. As far as I remember, BCD are just indicating start of the channel, and are therefore not really useful. IMO it would not hurt to keep them even if not too useful, just so imports are more predictable.

@3nids any opinion on that ? (I think you initially suggested to replicated that behavior ?)

**Comment by sjib** [comment]
@urskaufmann @DflGruBoe @varrieta @TriformMoritz @tproduit What do you think? Maybe software like Dataver is using also starting codes for interpretation? What is your experience with TV channel data as GEP engineers?

**Comment by urskaufmann** [comment]
In my opinion, individual codes should not already be filtered with the import. I want to take over the entire protocol. Often the BCD (beginning of the pipe) and BCE (end of the pipe) will be deleted or filtered. But it is possible, that these codes are also used e.g. for an intermediate shaft and that the shaft dimensions can be read from the BCD / BCE.

**Comment by 3nids** [comment]
Would it make sense to have it as an option?

**Comment by sjib** [comment]
From a engineers perspective the code BCD (start of pipe) is essential as it has to be in every inspection and bundles all coming codes. If you get to the end of a reach with the TV camera there has to be also the code BCE (end of pipe). If someone wants to make an evaluation of all damage codes on a pipe the start point is essential.

```
BCD (Rohranfang) ist der einzige Code, der wirklich in jeder Inspektion vorkommen muss. 
Das Du überhaupt eine Auswertung machen kannst, musst Du wissen wo der Rohranfang ist.
Und wenn der Operateur bis ans Rohrende kommt muss auch BCE zwingend
```
So not importing the BCD code in QGEP for me is not an option as we would delete essential information.

**Comment by 3nids** [comment]
I don't mind leaving them but I really don't understand what valuable information it brings.

>  bundles all coming codes

what do you mean?

Can you detail what essential information it brings?
is it that an inspection could start somewhere else than at the beginning of the pipe? if so, what does it change in terms of data?

**Comment by sjib** [comment]
`But it is possible, that these codes are also used e.g. for an intermediate shaft and that the shaft dimensions can be read from the BCD / BCE.`

We are loosing information that is in the BCD / BCE code.

Make an option if others think that is not necessary. I will need it to have BCE in the database. @urskaufmann also.

**Comment by sjib** [comment]
Here the description out of the relevant norm for BCD
[VSA_Schadencodierung page 26-29.pdf](https://github.com/QGEP/qgepqwat2ili/files/6699444/VSA_Schadencodierung.page.26-29.pdf)

**Comment by sjib** [comment]
You will need the BCD / BCE code also for visualisations like this:
[Kanalfernsehbericht_VSA-KEK.pdf](https://github.com/QGEP/qgepqwat2ili/files/6699458/Kanalfernsehbericht_VSA-KEK.pdf)
