### ISSUE TITLE
testdata_vsa_kek_2019_channel_damage_8486_identifierref import

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#9]
Entry in re_qgep_od.re_maintenance_event_wastewater_structure was created:

![testdata_vsa_kek_2019_channel_damage_8486_identifierref_045_21052021_170411](https://user-images.githubusercontent.com/1265865/119158628-b3b6fd80-ba56-11eb-8b12-dcab0585ae23.jpg)

![testdata_vsa_kek_2019_channel_damage_8486_identifierref_046_21052021_170548](https://user-images.githubusercontent.com/1265865/119158739-d34e2600-ba56-11eb-836e-4f13b2263fae.jpg)

**Comment by sjib** [comment]
![testdata_vsa_kek_2019_channel_damage_8486_identifierref_047_21052021_171802](https://user-images.githubusercontent.com/1265865/119160455-971bc500-ba58-11eb-9a9d-f8bcb7827cb3.jpg)

Channel (Wastewater_Structure).obj_id = ch13p7mzCL004313

**Comment by olivierdalang** [comment]
@sjib Not clear to me what this issue is about ?

**Comment by sjib** [comment]
@olivierdalang It is only a documentation that it works as expected. Therefore the label documentation!
